# Site settings
title: 若思夢
description: 世界上最美的女人！
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/blog/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://luchongyao.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: iforeteller #github username
repo: iforeteller #github repository
branch: master #branch
relative_source: ../blog/ #source directory
destination: ../index// #destination directory
production_url:  https://luchongyao.com/
source_url:  https://github.com/iforeteller #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml